services:
  - type: web
    name: agrof-frontend
    env: node
    buildCommand: npm install && npm run build:web
    startCommand: npx serve dist -s
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
