[Interface]
PrivateKey = oPR4HblJV7NirdocznX40NSAvpPc2BdEHiYYg84iMEs=
Address = 10.0.0.3/32

[Peer]
PublicKey = 70Slp9m69LmX/QnlxFnwzB12BiVmb/e8GBnuumXsbyo=
Endpoint = 102.209.111.210:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25

