#!/bin/bash

# Insert remaining herbicide products (11-54) into the array
HERBICIDE_SCREEN="/home/darksagae/Desktop/agrof-main/agrof-main/mobile/app/screens/HerbicidesScreen.js"

# Create the remaining products (11-54)
cat > /tmp/remaining_products_insert.js << 'EOF'
    },
    {
      id: 11,
      name: 'Butanil-70 - Selective Pre-and Post-emergence Herbicide Weed Control In Rice',
      image: herbicideImages['butanil_70_selective_pre_and_post_emergence_herbicide_weed_control_in_rice'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 12,
      name: 'Butanil S - Pre-emergence Herbicide For Weed Control In Rice, Maize, Groundnuts, Wheat, Soy Bean And Beans',
      image: herbicideImages['butanil_s_pre_emergence_herbicide_for_weed_control_in_rice_maize_groundnuts_wheat_soy_bean_and_beans'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 13,
      name: 'Clean Force',
      image: herbicideImages['clean_force'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 14,
      name: 'Cleanspray 720 Sl – Herbicide For Weed Control In Wheat, Maize, Rice And Plantation Crops',
      image: herbicideImages['cleanspray_720_sl_herbicide_for_weed_control_in_wheat_maize_rice_and_plantation_crops'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 15,
      name: 'D-amine 720% Sl',
      image: herbicideImages['d_amine_720_sl'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 16,
      name: 'Dualgold 960 Ec - Herbicide For Control Of Annual Grass Weeds In Maize',
      image: herbicideImages['dualgold_960_ec_herbicide_for_control_of_annual_grass_weeds_in_maize'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 17,
      name: 'Excel Glycel',
      image: herbicideImages['excel_glycel'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 18,
      name: 'Fennut 120 Sl',
      image: herbicideImages['fennut_120_sl'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 19,
      name: 'Force Top',
      image: herbicideImages['force_top'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    },
    {
      id: 20,
      name: 'Force Up',
      image: herbicideImages['force_up'],
      description: 'Agricultural herbicide for effective weed control.',
      price: 'Contact for pricing',
      packaging: 'Contact for pricing',
      category: 'Herbicide',
      manufacturer: 'Contact for details',
      activeIngredient: 'Contact for details',
      formulation: 'Contact for details',
      targetCrops: 'Contact for details',
      targetWeeds: 'Contact for details',
      applicationMethod: 'Contact for details',
      preHarvestInterval: 'Contact for details'
    }
  ];
EOF

echo "Remaining herbicide products (11-20) added successfully!"
echo "Need to add 34 more products (21-54)"
